// packages/react-components/src/control/Copy/Copy.tsx
import { type ReactNode, useState } from "react";
import "./Copy.scss" with { type: "text" };

type Props = {
	text: string;
};

export function Copy(props: Props): ReactNode {
	const [done, flip] = useState(false);
	const grab = () => {
		navigator.clipboard.writeText(props.text);
		flip(true);
		setTimeout(() => flip(false), 1600);
	};
	return (
		<button
			className={done ? "copy done" : "copy"}
			type="button"
			onClick={grab}
		>
			{done ? "copied" : "copy"}
		</button>
	);
}

// packages/design/src/focus/Copy/Copy.svelte
<script lang="ts">
	import Sign from "../../mark/Sign/Sign.svelte";
	import "./Copy.scss";

	let { text }: { text: string } = $props();
	let done = $state(false);

	function grab(): void {
		void navigator.clipboard.writeText(text);
		done = true;
		setTimeout(() => (done = false), 1600);
	}
</script>

<button class:done class="copy" type="button" onclick={grab}><Sign name={done ? "tick" : "copy"} />{done ? "copied" : "copy"}</button>
