// packages/design/src/focus/Search/Search.svelte
<script lang="ts">
	import "./Search.scss";

	let {
		value = $bindable(""),
		change,
		hint,
	}: {
		value?: string;
		change?: (next: string) => void;
		hint?: string;
	} = $props();

	function take(next: string): void {
		value = next;
		change?.(next);
	}
</script>

<input class="search" type="search" {value} placeholder={hint} oninput={(event) => take(event.currentTarget.value)} />

// packages/react-components/src/control/Search/Search.tsx
import type { ReactNode } from "react";
import "./Search.scss" with { type: "text" };

type Props = {
	value: string;
	change: (next: string) => void;
	hint?: string;
};

export function Search(props: Props): ReactNode {
	return (
		<input
			className="search"
			type="search"
			value={props.value}
			placeholder={props.hint}
			onChange={(event) => props.change(event.target.value)}
		/>
	);
}
