// packages/design/src/focus/Button/Button.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import "./Button.scss";

	let {
		children,
		label = "",
		press = () => {},
		look = "solid",
		wide = false,
		busy = false,
		halt = false,
		submit = false,
	}: {
		children?: Snippet;
		label?: string;
		press?: () => void;
		look?: "solid" | "quiet";
		wide?: boolean;
		busy?: boolean;
		halt?: boolean;
		submit?: boolean;
	} = $props();
</script>

<button type={submit ? "submit" : "button"} class:button-wide={wide} class="button button-{look}" disabled={busy || halt} aria-busy={busy} onclick={press}>
	{#if children}{@render children()}{:else}{label}{/if}
</button>

// packages/react-components/src/control/Button/Button.tsx
import type { ReactNode } from "react";

type Props = {
	children?: ReactNode;
	label?: string;
	press?: () => void;
	tone?: "solid" | "quiet";
	wide?: boolean;
	busy?: boolean;
	submit?: boolean;
};

export function Button(props: Props): ReactNode {
	const tone = props.tone ?? "solid";
	const width = props.wide === true ? " button-wide" : "";
	return (
		<button
			type={props.submit === true ? "submit" : "button"}
			className={`button button-${tone}${width}`}
			disabled={props.busy}
			aria-busy={props.busy}
			onClick={props.press}
		>
			{props.children ?? props.label}
		</button>
	);
}
