// packages/react-components/src/content/Code/Code.tsx
import type { ReactNode } from "react";
import { Copy } from "../../control/Copy/Copy";

type Props = {
	children: string;
	name?: string;
	copy?: boolean;
};

function order(text: string, index: number): ReactNode {
	if (!text.startsWith("$ ")) {
		return `${text}\n`;
	}
	return (
		<span className="order" key={index}>
			<span className="sign">$</span>
			{`${text.slice(1)}\n`}
		</span>
	);
}

function body(text: string): ReactNode {
	if (!text.split("\n").some((line) => line.startsWith("$ "))) {
		return text;
	}
	return text.split("\n").map((line, index) => order(line, index));
}

export function Code(props: Props): ReactNode {
	const topped = props.name !== undefined || props.copy === true;
	return (
		<div className="code">
			{topped ? (
				<header>
					<span>{props.name}</span>{" "}
					{props.copy === true ? <Copy text={props.children} /> : null}
				</header>
			) : null}
			<pre>
				<code>{body(props.children)}</code>
			</pre>
		</div>
	);
}

// packages/design/src/content/Code/Code.svelte
<script lang="ts">
	import Copy from "../../control/Copy/Copy.svelte";
	import "./Code.scss";

	let { children, name, copy = false }: { children: string; name?: string; copy?: boolean } =
		$props();
	let lines = $derived(children.split("\n"));
	let orders = $derived(lines.some((line) => line.startsWith("$ ")));
</script>

<div class="code">
	{#if name !== undefined || copy}
		<header><span>{name}</span> {#if copy}<Copy text={children} />{/if}</header>
	{/if}
	<pre><code>{#if orders}{#each lines as line}{#if line.startsWith("$ ")}<span class="order"><span class="sign">$</span>{line.slice(1)}{"\n"}</span>{:else}{line}{"\n"}{/if}{/each}{:else}{children}{/if}</code></pre>
</div>
