// packages/react-components/src/surface/Board/Board.tsx
import type { ReactNode } from "react";

type Props = {
	title: string;
	brief?: string;
	children: ReactNode;
};

export function Board(props: Props): ReactNode {
	return (
		<section className="board">
			<header className="board-head">
				<h2 className="board-title">{props.title}</h2>
				{props.brief ? <p className="board-brief">{props.brief}</p> : null}
			</header>
			<div className="board-body">{props.children}</div>
		</section>
	);
}

// packages/design/src/enclose/Board/Board.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import "./Board.scss";

	let { title, line, children }: { title: string; line?: string; children: Snippet } = $props();
</script>

<section class="board"><header class="board-head"><h2 class="board-title">{title}</h2>{#if line}<p class="board-brief">{line}</p>{/if}</header><div class="board-body">{@render children()}</div></section>
